### ISSUE TITLE
pip install girder_worker fails on python3

### ISSUE THREAD

**Issue by opadron** [girder/girder_worker#170]
Steps to reproduce:

```
virtualenv -p python3 env
source env/bin/activate
pip install girder_worker
```

Example log output:
```
$ pip install girder_worker
Collecting girder_worker
  Downloading girder-worker-0.3.1.tar.gz (72kB)
    100% |████████████████████████████████| 81kB 426kB/s
Collecting celery>=3.1.23 (from girder_worker)
  Downloading celery-4.1.0-py2.py3-none-any.whl (400kB)
    100% |████████████████████████████████| 409kB 1.3MB/s
Collecting ete3>=3.0.0b35 (from girder_worker)
  Using cached ete3-3.0.0b35.tar.gz
Collecting networkx>=1.11 (from girder_worker)
  Using cached networkx-1.11-py2.py3-none-any.whl
Collecting Pillow>=3.2.0 (from girder_worker)
  Using cached Pillow-4.2.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pymongo>=3.2.2 (from girder_worker)
Collecting pytz>=2016.4 (from girder_worker)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Requirement already satisfied: requests[security]>=2.10.0 in ./env/lib/python3.6/site-packages (from girder_worker)
Requirement already satisfied: six>=1.10.0 in ./env/lib/python3.6/site-packages (from girder_worker)
Collecting wsgiref>=0.1.2 (from girder_worker)
  Downloading wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3_/fkjsppvs7dxfmp0bl53sg9zr0000gn/T/pip-build-uphjpzju/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/private/var/folders/3_/fkjsppvs7dxfmp0bl53sg9zr0000gn/T/pip-build-uphjpzju/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3_/fkjsppvs7dxfmp0bl53sg9zr0000gn/T/pip-build-uphjpzju/wsgiref/
```

Looks like something to do with wsgiref?

**Comment by opadron** [comment]
I am on Mac, btw.  Not sure if this issue is present on linux.

**Comment by cjh1** [comment]
girder_worker doesn't currently support python3. See #119

**Comment by opadron** [comment]
That would explain it.  Thanks, @cjh1; and sorry for the noise.

**Comment by danlamanna** [comment]
Girder Worker doesn't support Py3 yet, see #146 and #119.

**Comment by zachmullen** [comment]
@opadron https://github.com/girder/girder_worker/pull/115

**Comment by jbeezley** [comment]
For the record, @cjh1 was the winner.

**Comment by cjh1** [comment]
:racehorse:

**Comment by zachmullen** [comment]
Lest it get lost in the noise, it's worth noting that I linked a different PR, which has already been merged and addresses this issue directly. It has not made it into a release on pypi, but if it had, you would not see this error anymore.
