### ISSUE TITLE
Docker errors not percolating up correctly

### ISSUE THREAD

**Issue by mgrauer** [girder/girder_worker#185]
I was using item_tasks to ingest a Docker image, the error in the Girder Job logs were misleading, as they said "no such image", though to be fair, that was true ultimately.  The problem was there wasn't enough disk space on the device to build the Docker image.  When I ran the "docker pull" command manually on that machine, I was able to see that disk space was the problem through an error message, but that message didn't percolate up.  I'm not sure if that error could be captured and sent along though.

>[2017-09-02 19:59:38,578] ERROR: Error pulling Docker image cdeepakroy/slicer_cli_web_plugin:
[2017-09-02 19:59:38,590] ERROR: 404 Client Error: Not Found ("no such image: cdeepakroy/slicer_cli_web_plugin: No such image: cdeepakroy/slicer_cli_web_plugin:latest")
Traceback (most recent call last):
  File "/home/worker/girder_worker/girder_worker/plugins/docker/executor.py", line 28, in _pull_image
    client.images.pull(image)
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/docker/models/images.py", line 274, in pull
    return self.get('{0}:{1}'.format(name, tag) if tag else name)
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/docker/models/images.py", line 204, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/docker/api/image.py", line 262, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/docker/api/client.py", line 226, in _result
    self._raise_for_status(response)
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
ImageNotFound: 404 Client Error: Not Found ("no such image: cdeepakroy/slicer_cli_web_plugin: No such image: cdeepakroy/slicer_cli_web_plugin:latest")
ImageNotFound: 404 Client Error: Not Found ("no such image: cdeepakroy/slicer_cli_web_plugin: No such image: cdeepakroy/slicer_cli_web_plugin:latest")
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/worker/girder_worker/girder_worker/tasks.py", line 19, in run
    return core.run(*pargs, **kwargs)
  File "/home/worker/girder_worker/girder_worker/core/utils.py", line 123, in wrapped
    return fn(*args, **kwargs)
  File "/home/worker/girder_worker/girder_worker/core/__init__.py", line 183, in run
    task_outputs=task_outputs, **kwargs)
  File "/home/worker/girder_worker/girder_worker/plugins/docker/executor.py", line 262, in run
    _pull_image(image)
  File "/home/worker/girder_worker/girder_worker/plugins/docker/executor.py", line 28, in _pull_image
    client.images.pull(image)
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/docker/models/images.py", line 274, in pull
    return self.get('{0}:{1}'.format(name, tag) if tag else name)
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/docker/models/images.py", line 204, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/docker/api/image.py", line 262, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/docker/api/client.py", line 226, in _result
    self._raise_for_status(response)
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/worker/.virtualenvs/girder-worker/local/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)

**Comment by jbeezley** [comment]
Our error handling is [here](https://github.com/girder/girder_worker/blob/master/girder_worker/plugins/docker/executor.py#L27).  I think this is more of an issue with docker-py not raising a helpful exception.  Not sure if there is much we can do about that here.

**Comment by cjh1** [comment]
@jbeezley Is right we just provide what docker-py throws.
