### ISSUE TITLE
Resolve error that occurs when docker task is run as non-root user

### ISSUE THREAD

**Issue by cdeepakroy** [girder/girder_worker#24]
@zachmullen 

When i [run](https://github.com/girder/girder_worker/blob/master/girder_worker/plugins/docker/executor.py#L160) a docker task that uses matplotlib i get the following error:

```
Pulling docker image: dsarchive/histomicstk
Running container: "docker run -u 1000 -v /media/common/EmoryImageAnnotationPlatform/code/girder_worker/srclnx/tmp/tmp8mAMxi:/data dsarchive/histomicstk StandaloneColorDeconvolution --stainColor_3 "0.0, 0.0, 0.0" /data/A.png "0.65, 0.7, 0.29" "0.07, 0.99, 0.11" /data/stain_1.png /data/stain_2.png /data/stain_3.png"
Traceback (most recent call last):
  File "StandaloneColorDeconvolution/StandaloneColorDeconvolution.py", line 3, in <module>
    import skimage.io
  File "/build/miniconda/lib/python2.7/site-packages/skimage/io/__init__.py", line 15, in <module>
    reset_plugins()
  File "/build/miniconda/lib/python2.7/site-packages/skimage/io/manage_plugins.py", line 93, in reset_plugins
    _load_preferred_plugins()
  File "/build/miniconda/lib/python2.7/site-packages/skimage/io/manage_plugins.py", line 73, in _load_preferred_plugins
    _set_plugin(p_type, preferred_plugins['all'])
  File "/build/miniconda/lib/python2.7/site-packages/skimage/io/manage_plugins.py", line 85, in _set_plugin
    use_plugin(plugin, kind=plugin_type)
  File "/build/miniconda/lib/python2.7/site-packages/skimage/io/manage_plugins.py", line 255, in use_plugin
    _load(name)
  File "/build/miniconda/lib/python2.7/site-packages/skimage/io/manage_plugins.py", line 299, in _load
    fromlist=[modname])
  File "/build/miniconda/lib/python2.7/site-packages/skimage/io/_plugins/matplotlib_plugin.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/build/miniconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/build/miniconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 965, in rc_params
    fname = matplotlib_fname()
  File "/build/miniconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 794, in matplotlib_fname
    configdir = _get_configdir()
  File "/build/miniconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 649, in _get_configdir
    return _get_config_or_cache_dir(_get_xdg_config_dir())
  File "/build/miniconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 626, in _get_config_or_cache_dir
    return _create_tmp_config_dir()
  File "/build/miniconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 555, in _create_tmp_config_dir
    tempdir = os.path.join(tempdir, 'matplotlib-%s' % getpass.getuser())
  File "/build/miniconda/lib/python2.7/getpass.py", line 158, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1000'
```

A fix for the same error is reported [here](https://github.com/matplotlib/matplotlib/issues/5940) on the matplotlib repository but that wont be available until matplotlib 1.5.2 is released.

@jcfr proposed a fix to a similar problem [here](https://github.com/kylemanna/docker-aosp/pull/11#issue-149828608)

**Comment by jcfr** [comment]
Assuming the docker images you are running does not already have an entrypoint, you could do something like this:

```
docker run -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v /path/to/docker_entrypoint.sh:/root/docker_entrypoint.sh:ro --entrypoint /root/docker_entrypoint.sh  imagename command args
```

See also https://docs.docker.com/engine/reference/run/#entrypoint-default-command-to-execute-at-runtime

You could generalize the `docker_entrypoint.sh` I created by adding it to `girder_worker` repo. May be a new name could be `docker_userconf_entrypoint.sh` ? 

On a related topic: https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine

**Comment by zachmullen** [comment]
Is there some way inside your image to make it so that matplotlib doesn't try to lookup the user from the password database? It looks like it's trying to create a temp directory and wants to include the user's name in the directory name, is there maybe some way to explicitly instruct matplotlib (maybe via environment variable) to not do this behavior? 

There is a general solution to this that would support container operations performing system user lookups, but it's dirty. Namely, we could inject a shell script into the container via the temp dir mounted volume. This script would first create a new user with the given UID if one did not already exist, then the script would delete itself and run whatever the client-specified entrypoint was.

Let me know if you foresee any problems with that hack, or if there is an easier way.

**Comment by zachmullen** [comment]
@jcfr beat me to it :)

**Comment by jcfr** [comment]
Cc: @thewtex
