### ISSUE TITLE
GirderFileIdToVolume should support ObjectId

### ISSUE THREAD

**Issue by zachmullen** [girder/girder_worker#242]
When calling `docker_run.delay` with `GirderFileIdToVolume`, the worker errors out if an `ObjectId` is passed for the file ID rather than a string. Since on the Girder side we try to deal with `ObjectId` everywhere, we should support this in the worker. Trace:

```
[2018-01-17 16:31:56,541: ERROR/ForkPoolWorker-3] Task girder_worker.docker.tasks.docker_run[9de95ecb-5ea9-48e5-860d-b11acb2b8090] raised unexpected: AttributeError("'ObjectId' object has no attribute 'startswith'",)
Traceback (most recent call last):
  File "/Users/zach/dev/girder/ve/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/zach/dev/girder_worker/girder_worker/docker/tasks/__init__.py", line 237, in __call__
    super(DockerTask, self).__call__(*args, **kwargs)
  File "/Users/zach/dev/girder_worker/girder_worker/app.py", line 167, in __call__
    _t_kwargs = _walk_obj(kwargs, self._maybe_transform_argument)
  File "/Users/zach/dev/girder/ve/lib/python2.7/site-packages/girder_worker_utils/__init__.py", line 26, in _walk_obj
    if isinstance(obj, dict):
  File "/Users/zach/dev/girder/ve/lib/python2.7/site-packages/girder_worker_utils/__init__.py", line 26, in <dictcomp>
    if isinstance(obj, dict):
  File "/Users/zach/dev/girder/ve/lib/python2.7/site-packages/girder_worker_utils/__init__.py", line 29, in _walk_obj
    
  File "/Users/zach/dev/girder/ve/lib/python2.7/site-packages/girder_worker_utils/__init__.py", line 34, in _walk_obj
    return tuple(_walk_obj(list(obj), func, leaf_condition=leaf_condition))
  File "/Users/zach/dev/girder_worker/girder_worker/docker/tasks/__init__.py", line 200, in _maybe_transform_argument
    arg, task=self, _default_temp_volume=self.request._default_temp_volume)
  File "/Users/zach/dev/girder_worker/girder_worker/app.py", line 157, in _maybe_transform_argument
    return arg.transform(**kwargs)
  File "/Users/zach/dev/girder_worker/girder_worker/docker/transforms/girder.py", line 60, in transform
    dir, self._file_id)
  File "/Users/zach/dev/girder/ve/bin/../lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'ObjectId' object has no attribute 'startswith'
```

**Comment by zachmullen** [comment]
ping @cjh1 @kotfic
