### ISSUE TITLE
Girder Client 2.4.0 breaking integration test

### ISSUE THREAD

**Issue by kotfic** [girder/girder_worker#333]
`girder_client>2.3.0` introduces a bug in in the `test_docker.py::test_docker_run_file_upload_to_item[admin-admin]` integration test.  This needs to be run down and we need to remove the pinning

```
gw_integration_test_girder_worker | [2019-03-07 21:36:49,985: ERROR/ForkPoolWorker-13] Task girder_worker.docker.tasks.docker_run[116c595f-5128-4155-87cb-519ae721e13c] raised unexpected: AttributeError("'GirderClient' object has no attribute '_serverVersion'",)
gw_integration_test_girder_worker | Traceback (most recent call last):
gw_integration_test_girder_worker |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
gw_integration_test_girder_worker |     R = retval = fun(*args, **kwargs)
gw_integration_test_girder_worker |   File "/girder_worker/girder_worker/docker/tasks/__init__.py", line 270, in __call__
gw_integration_test_girder_worker |     super(DockerTask, self).__call__(*args, **kwargs)
gw_integration_test_girder_worker |   File "/girder_worker/girder_worker/task.py", line 158, in __call__
gw_integration_test_girder_worker |     for i, r in enumerate(results)])
gw_integration_test_girder_worker |   File "/girder_worker/girder_worker/docker/tasks/__init__.py", line 237, in _maybe_transform_result
gw_integration_test_girder_worker |     idx, result, _default_temp_volume=self.request._default_temp_volume)
gw_integration_test_girder_worker |   File "/girder_worker/girder_worker/task.py", line 134, in _maybe_transform_result
gw_integration_test_girder_worker |     return grh.transform(result, **kwargs)
gw_integration_test_girder_worker |   File "/girder_worker/girder_worker/docker/transforms/girder.py", line 242, in transform
gw_integration_test_girder_worker |     return super(GirderUploadVolumePathToItem, self).transform(path)
gw_integration_test_girder_worker |   File "/usr/local/lib/python2.7/dist-packages/girder_worker_utils/transforms/girder_io.py", line 84, in transform
gw_integration_test_girder_worker |     self.gc.uploadFileToItem(self.item_id, path, **self.upload_kwargs)
gw_integration_test_girder_worker |   File "/usr/local/lib/python2.7/dist-packages/girder_client/__init__.py", line 926, in uploadFileToItem
gw_integration_test_girder_worker |     return self._uploadContents(obj, f, filesize, progressCallback=progressCallback)
gw_integration_test_girder_worker |   File "/usr/local/lib/python2.7/dist-packages/girder_client/__init__.py", line 1040, in _uploadContents
gw_integration_test_girder_worker |     if self.getServerVersion() >= ['2', '2']:
gw_integration_test_girder_worker |   File "/usr/local/lib/python2.7/dist-packages/girder_client/__init__.py", line 381, in getServerVersion
gw_integration_test_girder_worker |     if not self._serverVersion or not useCached:
gw_integration_test_girder_worker | AttributeError: 'GirderClient' object has no attribute '_serverVersion'

```

**Comment by kotfic** [comment]
Note that this includes in the `Dockerfile.girder_worker`  Dockerfile (why are we pip installing girder_client here)?

**Comment by zachmullen** [comment]
I'm looking into the upstream fix.

**Comment by zachmullen** [comment]
This has been fixed on master in g-client, just need to cut a release there.

**Comment by jbeezley** [comment]
A new one (3.0.0a4) will be out shortly.

**Comment by zachmullen** [comment]
I was wrong anyway, whatever was running in the integration test environment is *not* v2.4.0. Not sure what it was.

**Comment by kotfic** [comment]
This ended up being a combination of issues where a 2.x-maintenance branch version of girder_client was being serialized on the girder side,  then deseriailzied as a master branch version of girder_client on the worker side.  Even once this issue is fixed having a master branch version of GC talking to a 2.x-maintenance branch appears to throw errors around the `system/version` endpoint but i didn't dig too deep into that.  Just pinned to tip of 2.x-maintenance and moved on.

**Comment by zachmullen** [comment]
Ah, that does explain what I was seeing, thanks for the explanation.
